version: '3'

services:
  nextjs:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Update this with your actual domain when you have one
      - NEXT_PUBLIC_SITE_URL=http://localhost

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nextjs 